import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home({ movies }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Primary Page using Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>sssssasdssddss  

      <ul>
        {movies.results.map((movies) => (<li key={movies.id}><Link href={`/movies/${movies.id}`}><a>{movies.title}</a></Link>
        </li>
        ))}
      </ul>


    </div>
  )
}
export const getStaticProps = async () => {
  const response = await fetch('https://api.themoviedb.org/3/movie/popular?api_key=d416af5d4faee64e25ab001d87aab5c3')

  const movies = await response.json()

  return {
    props: {
      movies
    }
  }
}